### ISSUE TITLE
Add documentation entry for "MyST vs Sphinx"

### ISSUE THREAD

**Issue by agoose77** [jupyter-book/mystmd#1094]
In a [The Turing Way working group meeting](https://hackmd.io/VHYQp5EASQ-VQp7yEbWTLA?both#11-04-2024-Infrastructure-Working-Group-Meeting-13), it was put to me
> What is the difference between MyST and Sphinx

I gave an answer, but I don't think it was concise enough. We should probably have something to hand as it's a natural question!

**Comment by jnywong** [comment]
Hey @agoose77,

I am sure you have given me a convincing explanation in the past, but I find the page under [Reference > Background](https://mystmd.org/guide/background) a useful reference! Maybe it's not very findable by users since it's buried beneath the Reference dropdown.
