### ISSUE TITLE
`node` warning about `punycode`

### ISSUE THREAD

**Issue by roaldarbol** [jupyter-book/mystmd#1166]
## Description
When I run myst start, I get a warning - no issues running, just a warning:
```
(node:12596) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Seems to be an issue only on `node` version >=21 (https://stackoverflow.com/questions/68774489/punycode-is-deprecated-in-npm-what-should-i-replace-it-with).

**Comment by rowanc1** [comment]
Tried to actually fix this tonight, couldn't get of node-fetch cjs version, and this isn't going to be updated.
https://github.com/node-fetch/node-fetch/pull/1793

Instead I quieted the error in a few places. Should be ok for a CLI to not show these.
