### ISSUE TITLE
Figure conversion darkens figure

### ISSUE THREAD

**Issue by roaldarbol** [jupyter-book/mystmd#1170]
## Description
Currently, if embedding (large) figures such as PDFs, the conversion step darkens them. It happens for both the web rendering and PDF generation with Typst.

## Proposed solution
Find the right settings for `imagemagick` which handles the conversion.

@rowanc1 previously pointed me to the code which is here:
https://github.com/executablebooks/mystmd/blob/77d4f58eb08e720ffacc5838f78e15777b00e33d/packages/myst-cli/src/utils/imagemagick.ts#L95
```
convert -density 600 -colorspace RGB ${image} -trim ${png}
```

**Comment by stefanv** [comment]
Note that the `convert` command is deprecation in ImageMagick v7 for `magick`.

The current flags all appear to work "as-is".

I do not observe the darkening; I wonder if this is related to the colorspace. Do you have an example image you can share?

**Comment by roaldarbol** [comment]
Yeah, I've written quite a bit about it on the Discord. Can add here too: :-)

If you're using `convert`, you're not getting any of the bug fixes, updates etc. that has been introduced in ImageMagick 7, but are stuck with the legacy IM6 edition of the command. Here's the differences between v6 and v7 magick: https://www.imagemagick.org/script/porting.php

And examples: With `convert -density 600 -colorspace RGB fig.pdf fig-2.webp`:
![](https://media.discordapp.net/attachments/1247486291130585088/1247961544810303549/fig-2.webp?ex=668ec142&is=668d6fc2&hm=8b204aef1855b12cdfe4087287d9d42646efb60d3456f2dc9a8b31928ac0d435&=&format=webp&width=1516&height=1138)

And with `magick -density 600 -colorspace RGB fig.pdf fig.webp`:
![](https://media.discordapp.net/attachments/1247486291130585088/1247961667724378112/fig.webp?ex=668ec15f&is=668d6fdf&hm=16c82a5de1489200c91f56c6386f1dd4c4fcc85d3f6e1f752525e6f8d0177d22&=&format=webp&width=1516&height=1138)

**Comment by rowanc1** [comment]
#1388 should fix this!

https://github.com/user-attachments/assets/981501ff-4ba3-4e47-82ae-b6f8aca3b541
