### ISSUE TITLE
Unable to select or enter Yes when asked to run myst start

### ISSUE THREAD

**Issue by VRConservation** [jupyter-book/mystmd#1176]
Latest version. Unable to enter Y/n when running myst (must init). Can't type anything in the (Y/n) is greyed out. Have tried uninstalling and reinstalling. This is in the anaconda CLI but I've tried running it in VS Code terminal and power shell. Thanks for any help.

**Comment by rowanc1** [comment]
Very strange, thanks for the report. As a stop gap you can pass in `myst init -y`. After you `init` there shouldn't be any prompts for `myst start` or `myst build`.

**Comment by VRConservation** [comment]
Thanks. If I pass "myst init -y" I get "error: unknown option '-y'". Below is the screenshot of passing myst or myst init and I'm unable to enter or type anything and have to close the cli. NPM does show above.

[A screenshot of a computer program  Description automatically generated]

**Comment by rowanc1** [comment]
The current work around to this is to install using `npm`, the problem turns out to be in the python wrapper.

**Comment by rowanc1** [comment]
I am closing this to continue the tracking in #1425.
