### ISSUE TITLE
Python Plugins for MyST

### ISSUE THREAD

**Issue by rowanc1** [jupyter-book/mystmd#1298]
Currently we have plugins that work in the Javascript ecosystem, however, many of the users that we will be supporting are more familiar with Python, we ideally want to support plugins that feel easy to write for folks already familiar with Python.

In working with @agoose77 today, we put together a bit of a plan for getting python plugins for MyST transforms and directives. @agoose77 created a demo here which creates a gallery based on a collection of myst projects:

https://gist.github.com/agoose77/66700b2a172b4c11d4801f742534e4f7

The approach is to serialize the AST and pass it to a python process for transformation, and then carry on with other transformation in myst. This seems to work quite well from the first prototypes. I know @agoose77 has a lot more ideas on how to better integrate these things!

cc @jmunroe @jnywong @jukent @kafitzgerald

**Comment by agoose77** [comment]
This actually would be _super_ trivial to support out of the box with pyodide.

We just need to add support for `.py` plugins, and use Pyodide to load them. I won't start this yet because it's not super urgent.
