### ISSUE TITLE
allow dropdown admonitions to start open

### ISSUE THREAD

**Issue by parmentelat** [jupyter-book/mystmd#1319]
currently an admonition declared with `:class: dropdown` always starts closed
there are cases where it makes sense to have both the ability to open/close *and* to start open

## Proposal

add an `:open: ` flag to the `admonition` directive; its default would then be `false` if the `dropdown` class is mentioned, and `false` otherwise

**Comment by rowanc1** [comment]
Should have a fix for this out soon. Thanks for the report!

**Comment by parmentelat** [comment]
hey there
thanks for closing this
can you please elaborate on how to use this feature ?
I have tried

    ```{admonition} some title
    :class: dropdown
    :open:
    
    some text
    ```

but to avail apparently; maybe I don't have the right version of things, what's the requirement ?

thanks again :)

**Comment by rowanc1** [comment]
Try a `myst clean --templates` and then restart. I believe it is released!

The theme does need to be updated for it to work!
