### ISSUE TITLE
Raw html tags like kbd transformed into paragraphs in certain cases

### ISSUE THREAD

**Issue by nthiery** [jupyter-book/mystmd#1400]
In certain cases, the raw html tag `<kbd>F</kbd>` gets transformed to `<p><code>F</code></p>`, which forces paragraph breaks. This affects other tags like `<code>`,  `<i>` or `<b>`, ...

Myst version: 1.2.9; also version currently deployed on mystmd.org

## How to reproduce

Inputing the following in the sandbox of mystmd.org:
```
-  Cliquez dans la cellule ci-dessous, puis tapez <kbd>Maj</kbd>+<kbd>Entrée</kbd>
```
Produces:
![image](https://github.com/user-attachments/assets/87d66dd5-1a91-477a-bf38-4ff8a5c246c8)

It would be expected to have everything in a single line as in:
![image](https://github.com/user-attachments/assets/bc2d8b24-4e83-4499-8d28-e4e0de904799)

**Comment by nthiery** [comment]
Btw: is there a reason to change `<kbd>` to `<code>`? This discards semantic.

Thanks in advance!

**Comment by katjabercic** [comment]
To get an overview (not exhaustive) of the behaviour, paste the following into the [sandbox](https://mystmd.org):

```
Bad tags: <code>code</code>, <kbd>kbd</kbd>, <b>b</b>, <strong>strong</strong>, <i>i</i>, <em>em</em>, <a href="https://mystmd.org">myst</a>

Good tags: <sup>sup</sup>, <span>span</span>, <em>em</em>

- Bad tags: <code>code</code>, <kbd>kbd</kbd>, <b>b</b>, <strong>strong</strong>, <i>i</i>, <em>em</em>, <a href="https://mystmd.org">myst</a>
- Good tags: <sup>sup</sup>, <span>span</span>

1. Bad tags: <code>code</code>, <kbd>kbd</kbd>, <b>b</b>, <strong>strong</strong>, <i>i</i>, <em>em</em>
2. Good tags: <sup>sup</sup>, <span>span</span>

:::{tip}
Bad tags: <code>code</code>, <kbd>kbd</kbd>, <b>b</b>, <strong>strong</strong>, <i>i</i>, <em>em</em>

Good tags: <sup>sup</sup>, <span>span</span>
:::
```

**Comment by rowanc1** [comment]
These will all be fixed shortly:

![image](https://github.com/user-attachments/assets/53eaa663-2fc6-4840-a358-85dac8d9b011)

**Comment by nthiery** [comment]
Nice! That was superquick! Thanks :-)
