### ISSUE TITLE
Myst fails to start with Snap node installation

### ISSUE THREAD

**Issue by cliffckerr** [jupyter-book/mystmd#1419]
If you've install NodeJS via Snap on Ubuntu, Myst (v1.3.1) fails to find the correct location of the Node executable.

## Description

Specifically, in `main.py`, `shutil.which("node")` resolves to `/snap/bin/node`, which is set as `NODE_LOCATION`. But then `node = pathlib.Path(NODE_LOCATION).resolve()` resolves to `/usr/bin/snap`, and then `_version = subprocess.run([node, "-v"], capture_output=True, check=True, text=True).stdout` fails because it calls `snap` rather than `node`.

## Proposed solution

If you remove the `resolve()` call on the `Path` object, then it works. But I don't know if that would break other workflows.

**Comment by agoose77** [comment]
It looks like Snap uses the executable name (`argv[0]`) to figure out which binary to call; all symlinks resolve to `/usr/bin/snap`. So, if we want to support installation on snap, then _we_ want to avoid resolving the symlink. I don't _think_ we need to resolve this symlink, though; we should just be able to execute it. 

In the meantime, you can install `mystmd` from e.g. npm, which will avoid the Python wrapper.
