### ISSUE TITLE
[Typst] Subscript only uses first letter

### ISSUE THREAD

**Issue by roaldarbol** [jupyter-book/mystmd#1437]
## Description
When working in `math` environment, subscript (and probably also superscript) only uses the first symbol, even if more is in curly braces. E.g. the following works well in HTML, but not in Typst:
```
:::{math} 
:name: ch3-eq1

\text{SR} = \frac{\sum{t_{active}}}{\sum{t_{active}} + \sum{t_{passive}}}
:::
```

<img width="555" alt="Screenshot 2024-08-09 at 14 37 52" src="https://github.com/user-attachments/assets/833ab774-1c31-4b0b-84e2-6ec42f551ca9">

**Comment by rowanc1** [comment]
Should be fixed in #1439 when that goes live.
