### ISSUE TITLE
Some links (top nav, favicon, etc) don't use `BASE_URL` and are broken

### ISSUE THREAD

**Issue by lwasser** [jupyter-book/mystmd#1449]
If you go to our pyOpenSci [metrics dashboard](https://www.pyopensci.org/peer-review-metrics/) you can see that the top level navigation doesn't seem to register the base_url repo name which is the "folder" or path required to resolve the metrics dashboard -- pyopensci.org/peer-review-metrics. However the side bar on the right does resolve the base_url properly. 

You can see the github action that we are using [here](https://github.com/pyOpenSci/peer-review-metrics/blob/main/.github/workflows/deploy.yml) if you wish to test the action or see the action logs.

## Proposed solution
Ideally the base_url should register properly for every drop down link and base link in the top nav in addition to the toctree. 

## Additional notes

we discussed this in discord with @agoose77 and @choldgraf and it was determined to be a bug. please let me know if you want me to test anything!!

**Comment by lwasser** [comment]
Update - i just had a look at the raw html for our online metrics - it's not capturing the base_url for other elements too such as the favicon - (i think). the favicon for our site is in the images directory - i could move it to the root dir as well but it should be peer-review-metrics/favicon.ico (i think?)

`<link rel="icon" href="/favicon.ico">`

**Comment by rowanc1** [comment]
Partial fix in #1483 - the favicon was written as text not binary in the static builds. We also need to update the BASE_URL as you suggest.

**Comment by lwasser** [comment]
Thanks, @rowanc1. I'll l switch our build to install from github to test things out in the next few days.

**Comment by rowanc1** [comment]
It is released. I don't think it will work yet!

**Comment by lwasser** [comment]
Thank you!! I somehow thought it was fixed. I'll keep an eye on this. I realized it's not as simple as I thought to install mystmd from GitHub.

**Comment by rowanc1** [comment]
@lwasser this should be fixed relatively soon. Just put up a PR that we can deploy later this week.

**Comment by lwasser** [comment]
thanks @rowanc1 let me know when you'd like me to test things out 🚀 i've been seeing the quite release iterations - lots of work happening here!! 🚀

**Comment by rowanc1** [comment]
This will be released with the next mystmd release, likely next week. (my first fix didn't do the trick.. ☹)
