### ISSUE TITLE
Mishandling of certain characters in doc.title in PDF exports

### ISSUE THREAD

**Issue by nthiery** [jupyter-book/mystmd#1512]
I have a markdown document with a title containing less usual characters:
```
# TD 1 : Notion d'e'a«»algorithme
```
Then, in the pdf export (and in `-doc.title-`), the unbreakable space before the `:` is replaced by `ă`, single quotes are ignored, the `«` and `»`characters are replaced respectively by `ń` and `ż`. If instead the title is specified by a `title` metadata, then the single quotes are not ignored; the other characters are replaced as above.

The files are all encoded in UTF-8, and the template uses:
```
\usepackage[utf8]{inputenc} % allow utf-8 input
\usepackage[T1]{fontenc}    % use 8-bit T1 fonts
```

I can try to produce a minimal example if helpful.

**Comment by rowanc1** [comment]
Yes - a minimal example would be helpful and would inform our test cases. Even if it is just the title in markdown and what you would expect in latex.

Currently our titles are not full text, which may be part of the problem. We should be doing a better job at some of these conversions though, which is a little surprising. If you give us a few examples we will make them work. :)

**Comment by nthiery** [comment]
Hi @rowanc1,

I finally got the time to drill in. At the end of the day, it is an incompatibility between xelatex and fontenc
([that's the point of xelatex to not need these fonts workarounds](https://doc.ubuntu-fr.org/xelatex)] :
when compiling the following latex file, the title becomes `Works: éö Broken ă’‘ńż` in the pdf.
```
\documentclass{article}
\usepackage[T1]{fontenc}

\title{Works: éö Broken  '`«»}

\begin{document}
\maketitle
\end{document}
```

I am using a custom template derived from [that one](https://github.com/jupyter-book/mystmd/blob/918223b8fe0be431e0f647f00db4f9ebe10c8e86/packages/mystmd/tests/templates/tex/template.tex#L4) included in the myst sources, which turns out to use fontenc as above. Specifying no template or removing the use of fontenc in my custom template resolves the problem for me.

Thanks again for the feedback.

Presumably this ticket can be closed, unless the fontenc line should first be removed from the aforementioned template?
