### ISSUE TITLE
Footer link "made with MyST" broken

### ISSUE THREAD

**Issue by HelgeGehring** [jupyter-book/mystmd#1522]
In the footer, the link "made with MyST"  links to https://mystmd.org/made-with-myst, which gives a 404

mystmd: v1.3.8, same for https://mystmd.org/guide

## Description

link doesn't work

## Proposed solution

make link work or adjust link :D

**Comment by rowanc1** [comment]
It looks like the quickstart on websites was deleted in #1433 by @choldgraf. The content was moved around without the link being updated. I will updated the redirect now.

**Comment by HelgeGehring** [comment]
wow, that was quick :D
