### ISSUE TITLE
Search results have incorrect link if site is served on a subdomain via `BASE_URL`

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/mystmd#1544]
If a MyST site is deployed with a subdomain (e.g. `foo.org/mybook/`), then search result links are broken because the subdomain folder isn't added to the links.

For example, [see the 2i2c CZI report docs](https://2i2c.org/report-czi-2021/).

- The book is served at https://2i2c.org/report-czi-2021/
- The search results look like https://2i2c.org/year1#managed-hub-service-revenue

AKA, they are missing the `report-czi-2021/`, which is defined in the `BASE_URL` environment variable.

[Here's the documentation I followed](https://mystmd.org/guide/deployment-github-pages#example-a-full-github-action) to set up the `BASE_URL` parameter on github actions

**Comment by rowanc1** [comment]
Should be fixed with:

- https://github.com/jupyter-book/myst-theme/pull/475
