### ISSUE TITLE
Tabs / Admonition dropdowns / Headings from executable content

### ISSUE THREAD

**Issue by HelgeGehring** [jupyter-book/mystmd#1559]
Let's assume I have a notebook which analyzes a certain problem, but the problem depends on parameters.

I'd like to use the notebook to show the results for different parameters.

The easy way would be to just write a for loop which prints the results, but that would result in a super long page.
The other way would be to create multiple notebooks but that would lead to copied code.

## Proposal

Would it be possible to

- Have tabs on the notebook level, i.e. I specify in the header different parameters (like github actions matrix) and get back all the notebooks as one with tabs?
- Have a way to put the output of the scripts in tabs, i.e. embed https://mystmd.org/guide/dropdowns-cards-and-tabs#tabs somehow into the script?
- Is there a way to output headings within the executable content? (I.e. `print("## param 3"); ...; plt.plot()`

## Additional notes
Maybe there's also other ways to realize this?

**Comment by choldgraf** [comment]
I think that this issue covers the use-case that you want, is that right?

- https://github.com/jupyter-book/mystmd/issues/1026

If so, can we close this one and take the conversation over there? It definitely helps to hear your use-case for both planning + prioritizing!

**Comment by HelgeGehring** [comment]
Wow, that's exactly it! Amazing! I'll put my example there!

**Comment by choldgraf** [comment]
Great, thanks! (switching this one to "duplicate" closed status)
