### ISSUE TITLE
Use linkml for plugin types?

### ISSUE THREAD

**Issue by sneakers-the-rat** [jupyter-book/mystmd#1607]
## Proposal

Making a plugin, like what ya gone and done here.

It would be super lovely to be able to get types when writing an executable plugin in another language, no? what would y'all think about writing the type declarations for the plugin types in linkml, and then you can generate the typescript, pydantic models, json schema, etc. from linkml? 

## Additional notes

i would draft it and show ya how it works obviously :) just assessing curiosity

edit: also i suppose generally curious if there is already a python package rolling for plugin helpers? would like to contribute to it if it exists, if not i'll make it. want to make types and also some basic stuff like node navigation/etc. tools. lil wrapper things.

**Comment by agoose77** [comment]
I don't speak for the entire team, but my feeling on this is that it's a nice-to-have(!) but additional maintenance burden in the near term, especially whilst our schemas are evolving. The schemas you're talking about would be targetable with this kind of toolchain, but our main AST ideally needs to be first-hand TypeScript to make use of the `unified`/`mdast` ecosystem that leverages declaration merging for extensibility. 

That said, it would be nice to make authoring e.g. Python plugins easier, and these are the kinds of things that downstream developers could publish to help us move along. So, I for one would welcome any efforts here!

**Comment by sneakers-the-rat** [comment]
sounds reasonable <3

I shall start a package :)
