### ISSUE TITLE
Error when starting `myst`: `getaddrinfo ENOTFOUND api.mystmd.org`

### ISSUE THREAD

**Issue by agoose77** [jupyter-book/mystmd#1624]
### Discussed in https://github.com/executablebooks/MyST-Parser/discussions/998

<div type='discussions-op-text'>

<sup>Originally posted by **WiG96** November  5, 2024</sup>
i'm just starting with myST following this tutorial https://mystmd.org/guide/website-templates. I run into this error `request to https://api.mystmd.org/templates/site/myst/book-theme failed, reason: getaddrinfo ENOTFOUND api.mystmd.org`
![image](https://github.com/user-attachments/assets/2c6cb012-44b7-4d8b-a95d-8ea563059ca9)

myst.yml file : 

![image](https://github.com/user-attachments/assets/d6e40dca-4d6d-4b75-80c2-b5fcdf2f6b28)

</div>

@WiG96

**Comment by stevejpurves** [comment]
api is up and reachable: https://api.mystmd.org/ can you re-try from the same network?
otherwise could this be a DNS issue from the network that you're on?

**Comment by rowanc1** [comment]
I cannot reproduce this, perhaps our API was unavailable for a short time?

@WiG96 if this continues to be a problem, can you please reopen this?!
