### ISSUE TITLE
`span` content is parsed as a paragraph

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/mystmd#1627]
If you add `<span>` content to your document, it is correctly parsed, but its behavior is like a paragraph rather than a span because the preceding text has its `<p>` closed out.

For example, this:

```
Here's some <span class="col-gutter-right" style="font-weight:bold;">Span</span> content
```

Results in this outcome:

![Image](https://github.com/user-attachments/assets/732b2d64-d4e2-46bc-bc8d-d7300608a442)

And this HTML:

```html
<p>Here's some</p>
<span class="col-gutter-right" style="font-weight:bold">Span</span>
<p>content</p>
```

**Comment by rowanc1** [comment]
Interesting. This [demo](https://mystmd.org/sandbox?tab=demo&myst=SABlAHIAZQAnAHMAIABzAG8AbQBlACAAPABzAHAAYQBuACAAcwB0AHkAbABlAD0AIgBjAG8AbABvAHIAOgAgAHIAZQBkACIAPgBzAHAAYQBuADwALwBzAHAAYQBuAD4AIABjAG8AbgB0AGUAbgB0AA%3D%3D) seems to be working correctly.

**Comment by choldgraf** [comment]
This is no longer an issue! @rowanc1 correctly pointed out that the issue was I hadn't put a space in between two lines of my content!
