### ISSUE TITLE
Dark/light mode scrollbar of primary sidebar

### ISSUE THREAD

**Issue by jnywong** [jupyter-book/mystmd#1672]
## Proposal

Hellooo! I was updating my MyST website with the book theme enabled and noticed that the scrollbar of the expanded navigation menu on the left side was distractingly visible, especially in dark mode.

**Before:**

https://github.com/user-attachments/assets/7c9fbbb0-fdef-482d-a096-9632cdf38c3e

I propose to update the navigation scrollbar to a dark theme when switching to dark mode.

## Additional notes

See PR https://github.com/jupyter-book/myst-theme/pull/502.

**Comment by jnywong** [comment]
Pasted from https://github.com/jupyter-book/myst-theme/pull/502

> Happy to make a pr, but need some pointers on where to start because the light/dark mode theme switcher looks a little more complicated to contribute to at first glance.

**Comment by agoose77** [comment]
@jnywong yeah, if you're needing to change the DOM according to the theme, it is fiddly. But if it's just CSS changes, then you can use tailwind `dark:` selector to set a style that only applies for dark themes.
