### ISSUE TITLE
Content server port conflict if another server is being run on a port that myst tries to use 

### ISSUE THREAD

**Issue by agahkarakuzu** [jupyter-book/mystmd#1691]
Hi! 

I ran into this problem during `myst build`. The port for the theme server iterates according to availability (3001, 3002, etc.). 

However, if port `3100` is already occupied by another CDN, the myst build process does not attempt to use alternative ports such as `3101`, `3102`, etc. Instead, it continues to check for content on `localhost:3100`, resulting in conflicts. 

I tried to override this behaviour by setting `CONTENT_CDN_PORT` (say 3102) as an env var, but it did not take effect.  

https://github.com/jupyter-book/mystmd/blob/0dc62c76bdb6e10bae38b805df1d2594595c2f43/packages/myst-cli/src/build/site/start.ts#L153

Is there any way to enforce a specific content delivery port for a given myst build?

**Comment by agahkarakuzu** [comment]
@choldgraf quick note after seeing the title change. The other service on 3100 was also a (headless) myst cdn.

**Comment by choldgraf** [comment]
thank you for catching that! I was trying to make the title easier to quickly parse/search/etc :-)

**Comment by agahkarakuzu** [comment]
Quick update on this issue: 

* I moved the CDN (that runs as a background process) to port `3111`, yet `myst build` still failed despite that port `3100` was available. 
* The build succeeded when I stopped the `myst server` running on `3111`.

**Comment by agahkarakuzu** [comment]
Okay I finally figured out the problem! 

I had to isolate the env var defaults for the services running the background process manager (celery) and  myst (theme and cdn) services. 

Funny enough, the culprit was the `CONTENT_CDN` variable that I introduced. Removing this from the celery environment did the trick. As `myst build` commands were affected by it.

**Comment by choldgraf** [comment]
What's either the change to our documentation or the change in the codebase that would resolve this? It's not clear to me haha

**Comment by agahkarakuzu** [comment]
It is a change in my codebase that fixed it. 

On the documentation end, maybe making a note about isolating environment variables when multiple services are using myst would be a good idea. 

* Service-1 (`myst serve --headless`) sets `CONTENT_CDN` to force myst server an external url
* Service-2 (that lives on the same server, `myst build`) should not have `CONTENT_CDN` set. 

Then again, this is also falls under a more broader class of "good practices" in service management.

Either way, we can close this issue. Sorry for the spam :)

**Comment by choldgraf** [comment]
haha ok - thanks for doing a bit more digging and figuring out what was going on + reporting back. Probably saved somebody a few hours of fruitless debugging in the future :-)
