### ISSUE TITLE
Math equations cannot be labelled in lists

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [jupyter-book/mystmd#1693]
The following math equation is correctly rendered by myst, but the `(eq:HI_isotherms)` bit appears in the text instead of being interpreted as the equation's label:

```
* Integration along isotherms: $T$ is constant, $\rho$ varies. The Helmholtz free energy difference is given by
$$
F(\rho_2, T) - F(\rho_1, T) = N\int_{\rho_1}^{\rho_2} \frac{P(\rho)}{\rho^2} d\rho,
$$ (eq:HI_isotherms)
where the integrand can be obtained *e.g.* with canonical simulations.
```

I have tried prepending the equation with `(eq:HI_isotherms)=`, but that messes up the formatting, as the text that comes after the equation will not be interpreted as part of the same bullet point.

**Comment by agoose77** [comment]
To give an equation a label, you can use the
`directive` (https://mystmd.org/guide/math#math-directives) and set the `name` option), or use `\label{}` (https://mystmd.org/guide/math#dollar-math)

E.g. https://mystmd.org/sandbox?tab=demo&myst=KgAgAEkAbgB0AGUAZwByAGEAdABpAG8AbgAgAGEAbABvAG4AZwAgAGkAcwBvAHQAaABlAHIAbQBzADoAIAAkAFQAJAAgAGkAcwAgAGMAbwBuAHMAdABhAG4AdAAsACAAJABcAHIAaABvACQAIAB2AGEAcgBpAGUAcwAuACAAVABoAGUAIABIAGUAbABtAGgAbwBsAHQAegAgAGYAcgBlAGUAIABlAG4AZQByAGcAeQAgAGQAaQBmAGYAZQByAGUAbgBjAGUAIABpAHMAIABnAGkAdgBlAG4AIABiAHkACgAkACQACgBcAGwAYQBiAGUAbAB7AGUAcQA6AEgASQBfAGkAcwBvAHQAaABlAHIAbQBzAH0ACgBGACgAXAByAGgAbwBfADIALAAgAFQAKQAgAC0AIABGACgAXAByAGgAbwBfADEALAAgAFQAKQAgAD0AIABOAFwAaQBuAHQAXwB7AFwAcgBoAG8AXwAxAH0AXgB7AFwAcgBoAG8AXwAyAH0AIABcAGYAcgBhAGMAewBQACgAXAByAGgAbwApAH0AewBcAHIAaABvAF4AMgB9ACAAZABcAHIAaABvACwACgAkACQAIAAKAHcAaABlAHIAZQAgAHQAaABlACAAaQBuAHQAZQBnAHIAYQBuAGQAIABjAGEAbgAgAGIAZQAgAG8AYgB0AGEAaQBuAGUAZAAgACoAZQAuAGcALgAqACAAdwBpAHQAaAAgAGMAYQBuAG8AbgBpAGMAYQBsACAAcwBpAG0AdQBsAGEAdABpAG8AbgBzAC4ACgAKAFMAZQBlACAAQABlAHEAOgBIAEkAXwBpAHMAbwB0AGgAZQByAG0AcwAgAGYAbwByACAAbQBvAHIAZQA%3D

**Comment by lorenzo-rovigatti** [comment]
Thank you so much!
