### ISSUE TITLE
Nested documents

### ISSUE THREAD

**Issue by FreekPols** [jupyter-book/mystmd#1707]
## nested documents

I created a folder using git submodule. Working locally this works fine, however using the github pages, the modules in this subfolder are not loaded.

## Proposed solution
I follow this approach which works fine with JB: 
https://teachbooks.io/manual/external/Nested-Books/README.html

Somehow the redirect to the other git repo should be included.

**Comment by agoose77** [comment]
Hi @FreekPols, could you share more information about what you're doing in your deploy step? I suspect that your deploy workflow is not recursively cloning submodules.

**Comment by FreekPols** [comment]
Fixed it by including:
steps: 
  - name: Checkout Repository 
  - uses: actions/checkout@v4 
  - with: submodules: 'true' 
in the deploy file.

The result can be seen here:
https://contemporary-physicslab.github.io/TN2985/
The python modules are loaded from a different repository.
