### ISSUE TITLE
Clarify the options for static site hosting and "live server" hosting

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/mystmd#927]
## Proposal

The [deployments page in the documentation](https://mystmd.org/guide/deployment) has some guidance for how you can deploy a MyST book/article to the internet. It discusses a bit about "live" vs. "static" hosting, and then describes how to deploy to GitHub Pages and to CurveNote.

I think a few things could be improved to make it a bit clearer, so noting it here:

1. It could use a more in-depth description of the differences between a "live" app and a static website, but potentially moved to the bottom since it's probably not the most important information. Why / when would you want one vs. the other, etc.
2. Clarify that the "CurveNote" option is a "live app" option, not a static HTML option.
3. Describe how to deploy "live apps" on other common services like Netlify (I don't think it's possible on GitHub?)

**Comment by agoose77** [comment]
I took a look at answering this, but there are some nuances about what static vs dynamic means in this context that I'm not fully knowledgeable on. As such, I've released the self-assignment.
